-----SURE THE DATA IS EXCEST
USE GOLD_SILVER_PAT
GO
IF OBJECT_ID ('Silver.GOLD' , 'U') IS NOT NULL
DROP TABLE Silver.GOLD
GO

CREATE TABLE Silver.GOLD (
[DATE] DATE,
[CLOSE] DECIMAL (8,2) ,
[HIGH] DECIMAL (8,2) ,
[LOW] DECIMAL (8,2) ,
[OPEN] DECIMAL (8,2) ,
[VOLUME] int ,
[ASSET_TYPE] VARCHAR (10)
)
IF OBJECT_ID ('Silver.SILVER' , 'U' ) IS NOT NULL
DROP TABLE Silver.SILVER

GO

CREATE TABLE Silver.SILVER (
[DATE] DATE,
[CLOSE] DECIMAL (8,2) ,
[HIGH] DECIMAL (8,2) ,
[LOW] DECIMAL (8,2) ,
[OPEN] DECIMAL (8,2) ,
[VOLUME] int ,
[ASSET_TYPE] VARCHAR (10)
)