USE GOLD_SILVER_PAT
GO
EXEC BRONZE_LOAD_GS
GO
--INSERT DATA IN BRONZE LAYER----------------------------------
CREATE OR ALTER PROCEDURE BRONZE_LOAD_GS AS
BEGIN
  DECLARE @STARTLOAD DATETIME , @ENDLOAD DATETIME , @BATCHST DATETIME , @BATCHED DATETIME ; 
   BEGIN TRY
   PRINT'>>>>>LOAD THE BATCH '
SET @BATCHST = GETDATE();
--INSERT DATA IN GOLD TABLE-------------------------------------
SET @STARTLOAD = GETDATE();
PRINT '>>>TRUNCATE TABLE : GOLD';
TRUNCATE TABLE Gold;
PRINT '>>>INSERTING DATA IN TABLE : GOLD'
BULK INSERT Gold
FROM 'D:\New folder (12)\Gold_Prices_Since_1974.CSV'
WITH (
FIRSTROW = 4 ,
FIELDTERMINATOR = ',' ,
rowterminator = '0x0a',
TABLOCK
)
SET @ENDLOAD = GETDATE()
PRINT 'LOAD DURATION : ' + CAST (DATEDIFF(SECOND,@STARTLOAD,@ENDLOAD)AS VARCHAR ) +'SECOND';
--INSERT DATA IN SILVER TABLE-----------------------------------
SET @STARTLOAD = GETDATE() ;
PRINT '>>>TRUNCATE TABLE SILVER '
TRUNCATE TABLE Silver;
PRINT'>>>INSERT DATA IN TABLE : SILVER'
BULK INSERT Silver 
FROM 'D:\New folder (12)\Silver_Prices_Since_1974.csv'
WITH(
FIRSTROW = 4 ,
FIELDTERMINATOR = ',' ,
rowterminator = '0x0a',
TABLOCK
)
    SET @ENDLOAD = GETDATE();
 PRINT 'LOAD DURATION : ' + CAST (DATEDIFF(SECOND , @STARTLOAD , @ENDLOAD) AS VARCHAR) + 'SECOND' ; 
    
    SET @BATCHED = GETDATE();
PRINT'>>>>>THE LOAD DONE'
PRINT 'FULL LOAD DURATION' + CAST(DATEDIFF(SECOND, @BATCHST,@BATCHED)AS VARCHAR) + 'SECOND' ;
    END TRY
    BEGIN CATCH
    PRINT '=========================================='
		PRINT 'ERROR OCCURED DURING LOADING BRONZE LAYER'
		PRINT 'Error Message' + ERROR_MESSAGE();
		PRINT 'Error Message' + CAST (ERROR_NUMBER() AS NVARCHAR);
		PRINT 'Error Message' + CAST (ERROR_STATE() AS NVARCHAR);
		PRINT '=========================================='
    END CATCH
END